#!/usr/bin/env python3
"""Generate docker-compose.yml with a given number of Slurm compute node services.

Compose's --scale/deploy.replicas can't give each replica a unique hostname or
env var, which Slurm nodes need (distinct NodeName/SLURM_NODENAME). Rather than
work around that at runtime, this script generates one explicit service per
node, matching the NodeName=slurmnode[1-10] range configured in slurm.conf.

Usage:
    ./generate-compose.py [--nodes N] [--output FILE]
"""
import argparse

HEADER = """# Generated by generate-compose.py --nodes {nodes}. Do not hand-edit the
# slurmnode service blocks below; re-run the script to change the node count.
x-node-common: &node-common
  image: ghcr.io/noaa-gsl/dockerspackstackslurmcluster/slurm-spack-stack-node:ubuntu-${{UBUNTU_VERSION:-26.04}}-spack-stack-${{SPACK_STACK_VERSION:-2.1.0}}
  shm_size: '4g'
  user: admin
  volumes:
    - home-vol:/home/admin
    - opt-vol:/opt:ro
  depends_on:
    slurmmaster:
      condition: service_started
    slurmfrontend:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=no", "admin@localhost", "hostname"]
    interval: 2s
    timeout: 2s
    retries: 10
    start_period: 5s

services:
  slurmfrontend:
    build:
      context: ./frontend
      args:
        SPACK_BUILD_JOBS: 8
        BASE_IMAGE_TAG: ubuntu-${{UBUNTU_VERSION:-26.04}}-slurm-${{SLURM_VERSION:-25.11.5}}
        UBUNTU_VERSION: ${{UBUNTU_VERSION:-26.04}}
        SPACK_STACK_VERSION: ${{SPACK_STACK_VERSION:-2.1.0}}
      secrets:
        - github_token
    image: ghcr.io/noaa-gsl/dockerspackstackslurmcluster/slurm-spack-stack-frontend:ubuntu-${{UBUNTU_VERSION:-26.04}}-spack-stack-${{SPACK_STACK_VERSION:-2.1.0}}
    container_name: ${{CLUSTER_NAME:-spack-stack}}-frontend
    shm_size: '4g'
    hostname: slurmfrontend
    user: admin
    volumes:
      - home-vol:/home/admin
      - opt-vol:/opt
    healthcheck:
      # /tmp/ssh-ready is created by the base image entrypoint after munged + sshd are up
      # and the admin SSH keypair is written. The long start_period absorbs the multi-GB
      # initial copy of /opt (spack-stack install) into the empty opt-vol on first launch;
      # subsequent restarts reuse the populated volume and finish quickly.
      test: ["CMD", "test", "-f", "/tmp/ssh-ready"]
      interval: 5s
      timeout: 2s
      retries: 250
      start_period: 60s

  slurmmaster:
    build:
      context: ./master
      args:
        BASE_IMAGE_TAG: ubuntu-${{UBUNTU_VERSION:-26.04}}-slurm-${{SLURM_VERSION:-25.11.5}}
    image: ghcr.io/noaa-gsl/dockerspackstackslurmcluster/slurm-spack-stack-master:ubuntu-${{UBUNTU_VERSION:-26.04}}-spack-stack-${{SPACK_STACK_VERSION:-2.1.0}}
    container_name: ${{CLUSTER_NAME:-spack-stack}}-master
    shm_size: '4g'
    hostname: slurmmaster
    user: admin
    volumes:
      - home-vol:/home/admin
      - opt-vol:/opt:ro
    environment:
      - SLURM_CPUS_ON_NODE=8
    depends_on:
      slurmfrontend:
        condition: service_healthy
"""

FIRST_NODE_TEMPLATE = """
  slurmnode{n}:
    <<: *node-common
    build:
      context: ./node
      args:
        BASE_IMAGE_TAG: ubuntu-${{UBUNTU_VERSION:-26.04}}-slurm-${{SLURM_VERSION:-25.11.5}}
    container_name: ${{CLUSTER_NAME:-spack-stack}}-node{n}
    hostname: slurmnode{n}
    environment:
      - SLURM_NODENAME=slurmnode{n}
      - SLURM_CPUS_ON_NODE=8
"""

NODE_TEMPLATE = """
  slurmnode{n}:
    <<: *node-common
    container_name: ${{CLUSTER_NAME:-spack-stack}}-node{n}
    hostname: slurmnode{n}
    environment:
      - SLURM_NODENAME=slurmnode{n}
      - SLURM_CPUS_ON_NODE=8
"""

FOOTER = """
volumes:
  home-vol:
  opt-vol:

secrets:
  github_token:
    environment: GITHUB_TOKEN
"""

MAX_NODES = 10


def build_compose(nodes: int) -> str:
    if not 1 <= nodes <= MAX_NODES:
        raise ValueError(f"--nodes must be between 1 and {MAX_NODES} (slurm.conf defines NodeName=slurmnode[1-{MAX_NODES}])")
    parts = [HEADER.format(nodes=nodes)]
    parts.append(FIRST_NODE_TEMPLATE.format(n=1))
    parts.extend(NODE_TEMPLATE.format(n=i) for i in range(2, nodes + 1))
    parts.append(FOOTER)
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nodes", type=int, default=5, help="number of slurmnode services to generate (default: 5, max: %d)" % MAX_NODES)
    parser.add_argument("--output", default="docker-compose.yml", help="output file path (default: docker-compose.yml)")
    args = parser.parse_args()

    compose = build_compose(args.nodes)
    with open(args.output, "w") as f:
        f.write(compose)
    print(f"Wrote {args.output} with {args.nodes} node service(s).")


if __name__ == "__main__":
    main()
