name: PackageCleanup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/frontend
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/frontend'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/master
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/master'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/node
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/node'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/frontend-cache-amd64
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/frontend-cache-amd64'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/frontend-cache-arm64
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/frontend-cache-arm64'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/master-cache-amd64
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/master-cache-amd64'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/master-cache-arm64
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/master-cache-arm64'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/node-cache-amd64
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/node-cache-amd64'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of dockerspackstackslurmcluster/node-cache-arm64
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'dockerspackstackslurmcluster/node-cache-arm64'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
